### ISSUE TITLE
AppService documentation issue? Project has no peerDependencies.

### ISSUE THREAD

**Issue by jaller94** [turt2live/matrix-bot-sdk#111]
https://github.com/turt2live/matrix-bot-sdk#application-services

The section about AppServices starts with the instruction to install all `peerDependencies`, but the project does not seem to have any in `package.json`.

**Comment by Half-Shot** [comment]
I think express was likely a peerDependency at one point, but it was likely made a dependency.

**Comment by Half-Shot** [comment]
@turt2live this can be closed
