### ISSUE TITLE
TS2344 when using 0.6.0-beta.2

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-bot-sdk#155]
```
node_modules/matrix-bot-sdk/lib/e2ee/CryptoClient.d.ts:109:84 - error TS2344: Type 'unknown' does not satisfy the constraint 'Object'.

109     decryptRoomEvent(event: EncryptedRoomEvent, roomId: string): Promise<RoomEvent<unknown>>;
```

Apologies for filing an issue on a clearly-beta release, but this seems to be a blocker for using the lib in a TS environment.

**Comment by turt2live** [comment]
What is your tsconfig? I've used the beta in about 3 TS projects since launch with zero issues :s

**Comment by Half-Shot** [comment]
```

**Comment by turt2live** [comment]
hmm, strange. The `strict: true` might be doing it, but I guess it's a valid error. Going to handle this by changing the types of `RoomEvent` instead (as `Record<A, B>` is not my favourite).
