### ISSUE TITLE
Support binding the appservice listener to an existing express app.

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-bot-sdk#191]
Ideally, I'd like for the bot-sdk to export a Router object, which I could then bind via `expressApp.use` to my existing express instance. The need is for hookshot to support several different listeners on the same port.

**Comment by turt2live** [comment]
There's quite a lot of middleware which goes into running an appservice, and express is not guaranteed. The app instance is exposed by the bot-sdk as a short term solution.

**Comment by Half-Shot** [comment]
Okay, alternatively I need a way to pass in HTTP requests from my code into the appservice class somehow. Because of the same middleware, it's not easy to bind to the existing app instance.

**Comment by AndrewFerr** [comment]
Looks like this was fixed by https://github.com/turt2live/matrix-bot-sdk/pull/349?

**Comment by turt2live** [comment]
It was already technically supported, but buggy.
