### ISSUE TITLE
Bot can decrypt messages but sends messages without sending keys to other participants in the room

### ISSUE THREAD

**Issue by freelock** [turt2live/matrix-bot-sdk#196]
Reposting here from matrix:r/matrix-bot-sdk:t2bot.io.

I successfully set up the RustSdkCrptoStorageProvider on my bot, and the bot reads encrypted messages and operates the same as it did before, other than now being able to read all encrypted messages. However, when it responds in an encrypted room, the messages it sends cannot be decrypted by any other room member.

Am I missing some sort of setup step to get the bot to send keys to other room participants?

This is using the bot-sdk as described here: https://turt2live.github.io/matrix-bot-sdk/tutorial-encryption-bots.html

I have tried getting a new auth token (using curl to retrieve from the authentication endpoint) blowing the contents of the storage directory away each time.

I've also tried inviting the bot to brand new e2e rooms, and everything I could think of -- I'm seeing the same result in all cases -- the bot can read encrypted messages and respond, but the responses are not decryptable because "** Unable to decrypt: The sender's device has not sent us the keys for this message. **".

I've also tried with other user accounts on different homeservers. If I log into Element with the bot account, all the messages are decryptable for the bot users.

**Comment by nforgerit** [comment]
I can confirm this problem with the exact same setup. Any hints on what the problem could be?
