### ISSUE TITLE
Bot not responding to me

### ISSUE THREAD

**Issue by dzg** [turt2live/matrix-bot-sdk#200]
I'm using the code from [https://matrix.org/docs/guides/usage-of-matrix-bot-sdk](https://matrix.org/docs/guides/usage-of-matrix-bot-sdk)

My bot *does* auto-join a room when invited ... but *does NOT* respond to messages from me, and the `client.on("room.message"...` handler is NOT called.

But if I send a message to the room from another dummy user via API, then it does respond.

This is my first bot ... any ideas why it's ignoring messages from myself?

    client.on("room.message", (roomId, event) => {
        console.log(event); 
        const sender = event["sender"];
        const body = event["content"]["body"];
        console.log(`${roomId}: ${sender} says '${body}`);
    
        if (body.startsWith("!echo")) {
            const replyText = body.substring("!echo".length).trim();
            client.sendMessage(roomId, {
                "msgtype": "m.notice",
                "body": replyText,
            });
        }
    });

**Comment by turt2live** [comment]
*moved to room*

**Comment by anonimo0-0** [comment]
What?...
