### ISSUE TITLE
[Question] How do I disable logs?

### ISSUE THREAD

**Issue by dulguun0225** [turt2live/matrix-bot-sdk#217]
Hello, I want to disable logs like this
![image](https://user-images.githubusercontent.com/4142584/169233453-e58a82fa-eca3-4687-af2a-e6c99cb6cb87.png)

How do I do that?

**Comment by jaller94** [comment]
```js
const {
    LogLevel,
    LogService,
} = require('matrix-bot-sdk');

LogService.setLevel(LogLevel.ERROR);
```

This gives you only errors.
There is also `LogLevel.WARN`.

**Comment by turt2live** [comment]
These logs are coming from the appservice side, not the LogService stuff. It needs fixing.

**Comment by turt2live** [comment]
Fixed by https://github.com/turt2live/matrix-bot-sdk/pull/212
