### ISSUE TITLE
Still uses the unstable app service login (which was removed in Synapse 1.59)

### ISSUE THREAD

**Issue by sandhose** [turt2live/matrix-bot-sdk#230]
Synapse 1.59 deprecated [`uk.half-shot.msc2778.login.application_service`](https://github.com/matrix-org/synapse/pull/12597) since it was stabilised with the `m.login.application_service` identifier.

The bot-sdk is still using `uk.half-shot.msc2778.login.application_service` ([here](https://github.com/turt2live/matrix-bot-sdk/blob/c1dda88878373336726b0bc24154f8f9289520a0/src/appservice/Intent.ts#L150)), whereas it should probably use the stable one (or even better: discover them with a `GET /login`)

cc @turt2live

**Comment by turt2live** [comment]
Auto-discovery isn't really feasible for this code given the high traffic tbh.
