### ISSUE TITLE
client.getRoomMembers returns empty array when given `membership` to search for, but not otherwise

### ISSUE THREAD

**Issue by jakecoppinger** [turt2live/matrix-bot-sdk#234]
When I call `client.getRoomMembers(roomId,undefined,['invite', 'join'])` I get an empty array, though I get many events for `client.getRoomMembers(roomId, undefined)` (including those with `invite` or `join`).

Could there be an issue in the query strings being sent for `membership`?

**Comment by turt2live** [comment]
I can't reproduce this on the v0.6 beta - maybe it's been magically fixed?

The server receives the correct query:
`GET /_matrix/client/v3/rooms/!OUOlHKSYDAWhKACWud%3Alocalhost/members?membership=invite&membership=join`
