### ISSUE TITLE
`AutojoinRoomsMixin` feature to automatically join all rooms in one space

### ISSUE THREAD

**Issue by luphoria** [turt2live/matrix-bot-sdk#235]
I just today had an idea to make [my bot](https://github.com/luphoria/graim) easier to set up: allow it to automatically join all rooms in a space if invited to one (or, at the least, auto-join all of the rooms with the `auto_join` flag on). However, this required me to [stop using the `AutojoinRoomsMixin` SDK feature](https://github.com/luphoria/graim/commit/9064dc980a168dfd253c7113491e0d7566f63df4) and simply re-write that implementation in-house.
 
**Describe the solution you'd like**
An optional flag in the function `AutojoinRoomsMixin.setupOnClient` function (appservice?) to also automatically join all rooms in the space's `m.space.child` state.

**Additional context**
I wrote my own implementation which can be found in commit https://github.com/luphoria/graim/commit/9064dc980a168dfd253c7113491e0d7566f63df4 of graim. However, I didn't want to impede on any design choices of the SDK. Tell me what you think :)

**Comment by turt2live** [comment]
This doesn't appear to be a feature in the spec, and is indeed not used, so the field doesn't have meaning. 

Once the field does get meaning though, this can be a new mixin which does the required behaviour.

https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/1772-groups-as-rooms.md#auto-joined-children for historical context.
