### ISSUE TITLE
[v0.6.0-beta.8] "One time key signed_curve25519:AAAABw already exists."

### ISSUE THREAD

**Issue by CyberShadow** [turt2live/matrix-bot-sdk#237]
Hi, thanks for this project!

I'm trying to use it to write a bot which acts on my behalf to automate some things. As such, it runs under my account.

I noticed that the last stable version (`v0.5.9`) could not decrypt encrypted messages, so I'm trying `v0.6.0-beta.8`.

Upon adding a `RustSdkCryptoStorageProvider` instance and passing it to `MatrixClient`, it crashes printing this:

```
Fri, 01 Jul 2022 06:45:50 GMT [ERROR] [MatrixHttpClient (REQ-171)] {
  errcode: 'M_UNKNOWN',
  error: `One time key signed_curve25519:AAAABw already exists. Old key: {"key":"mPKa***************************************","signatures":{"@cybershadow:cy.md":{"ed25519:DYFH******":"r5Am**********************************************************************************"}}}; new key: {'key': 'IUFe***************************************', 'signatures': {'@cybershadow:cy.md': {'ed25519:DYFH******': '2z2W**********************************************************************************'}}}`
}
/home/vladimir/work/matrix-bot/node_modules/matrix-bot-sdk/lib/http.js:92
                reject(new MatrixError_1.default(errBody, response.statusCode));
                       ^
MatrixError: M_UNKNOWN: One time key signed_curve25519:AAAABw already exists. Old key: {"key":"mPKa***************************************","signatures":{"@cybershadow:cy.md":{"ed25519:DYFH******":"r5Am**********************************************************************************"}}}; new key: {'key': 'IUFe***************************************', 'signatures': {'@cybershadow:cy.md': {'ed25519:DYFH******': '2z2W**********************************************************************************'}}}
    at Request._callback (/home/vladimir/work/matrix-bot/node_modules/matrix-bot-sdk/lib/http.js:92:24)
    at self.callback (/home/vladimir/work/matrix-bot/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/home/vladimir/work/matrix-bot/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/home/vladimir/work/matrix-bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  body: {
    errcode: 'M_UNKNOWN',
    error: `One time key signed_curve25519:AAAABw already exists. Old key: {"key":"mPKa***************************************","signatures":{"@cybershadow:cy.md":{"ed25519:DYFH******":"r5Am**********************************************************************************"}}}; new key: {'key': 'IUFe***************************************', 'signatures': {'@cybershadow:cy.md': {'ed25519:DYFH******': '2z2W**********************************************************************************'}}}`
  },
  statusCode: 400,
  errcode: 'M_UNKNOWN',
  error: `One time key signed_curve25519:AAAABw already exists. Old key: {"key":"mPKa***************************************","signatures":{"@cybershadow:cy.md":{"ed25519:DYFH******":"r5Am**********************************************************************************"}}}; new key: {'key': 'IUFe***************************************', 'signatures': {'@cybershadow:cy.md': {'ed25519:DYFH******': '2z2W**********************************************************************************'}}}`,
  retryAfterMs: undefined
}
Node.js v18.3.0
```

Perhaps this is because I'm trying to run it on an existing user? To do this, I opened an Element instance in a private window, logged in as myself, got the token, approved the instance from another client (by comparing emoji), then closed the private window.

Also, I don't know if this is relevant or not, but I noticed that in the `signatures` object in the message above, I see instances with the same key (`'ed25519:DYFH******'`) but different values (`"r5Am..."` and `'2z2W...'`).

Hope this helps!

**Comment by turt2live** [comment]
The access token was already used to set up encryption for that device: a fresh access token may be required.

**Comment by CyberShadow** [comment]
Thanks, that works! Is it possible to verify the bot's device? And, is it possible to import E2E room keys into the bot?

**Comment by turt2live** [comment]
verification isn't supported, but manual verification of the bot is always a thing you can do. Importing room keys is also not supported at the moment.

**Comment by CyberShadow** [comment]
> verification isn't supported, but manual verification of the bot is always a thing you can do.

Sorry to bother you but could you please give me a pointer for how one would accomplish this?

Or, would it perhaps make more sense to use `matrix-rust-sdk` at this time? I found this project via https://matrix.org/docs/guides/usage-of-matrix-bot-sdk/ but I see now that it's not in the matrix/ namespace, and even uses `matrix-rust-sdk`'s crypto crate.

**Comment by Xavier4492** [comment]
> verification isn't supported, but manual verification of the bot is always a thing you can do. 

Hello, I've been looking for several days how to do this manually, but I can't find the right eventName to listen to "m.key.verification.request" nor any to_device event, what am I missing?
Is there a way to log all incoming events (not those for which a listener recorded)

Thanks for you job !! big stuff
