### ISSUE TITLE
Run matrix-bot-sdk in docker container node:18.7.0-alpine

### ISSUE THREAD

**Issue by fl-oe** [turt2live/matrix-bot-sdk#255]
**The bug**
I try to run the matrix-bot-sdk with encryption in a docker container.
I am using node:18.7.0-alpine docker image. The build process runs successfully, but then I am not able to start the container.

```usr/src/app/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:234
throw loadError
^

Error: Error relocating /usr/src/app/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/matrix-sdk-crypto.linux-x64-musl.node: __register_atfork: symbol not found

at Module._extensions..node (node:internal/modules/cjs/loader:1204:18)
at Module.load (node:internal/modules/cjs/loader:998:32)
at Module._load (node:internal/modules/cjs/loader:839:12)
at Module.require (node:internal/modules/cjs/loader:1022:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/usr/src/app/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:159:31)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
at Module.load (node:internal/modules/cjs/loader:998:32)
at Module._load (node:internal/modules/cjs/loader:839:12) {
code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.7.0
```

**To Reproduce**
I can not provide the whole project. But here is the Dockerfile.
```
FROM node:18.7.0-alpine  AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install glob rimraf

RUN npm install --only=development

COPY . .

RUN npm run build



FROM node:18.7.0-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV CHROME_BIN="/usr/bin/chromium-browser" \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production
RUN apk add --no-cache chromium

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]
```

**Expected behavior**
I would expect to be able to start the docker container with encryption.

**Comment by Half-Shot** [comment]
Hey, heads up on [matrix-hookshot](https://github.com/matrix-org/matrix-hookshot) we found that Alpine images do not play ball with native rust modules (like the crypto bits). There are some incompatibilities with the musl provided by alpine.

I would try using 18.7.0-slim and see if it runs.

**Comment by fl-oe** [comment]
Hi. Thanks for your suggestion to use 18.7.0-slim. I am now using 18.7.0 and it is working fine. Thanks.

**Comment by deepbluev7** [comment]
There is no issue with the musl from alpine, the matrix-sdk-crypto-nodejs binaries are just built against glibc instead of musl. If you rebuild them manually, they work fine.
