### ISSUE TITLE
How to delete or edit a message sent by the bot ?

### ISSUE THREAD

**Issue by jdkcoder** [turt2live/matrix-bot-sdk#259]
I'm creating a bot on Element.io with TypeScript and I tried to find method to edit or delete sent message in documentation on both Turt2live & Matrix's official website but these methods are still invisible. So, please tell me is there any ways to delete or edit a sent message?

**Comment by turt2live** [comment]
"Deletion" is actually just redaction. Edits are not yet supported directly with the SDK, but can be sent manually using events.
