### ISSUE TITLE
matrix-js-sdk uses an unspecced `original_event` field from the `/relations` response

### ISSUE THREAD

**Issue by clokep** [turt2live/matrix-bot-sdk#263]
The [`/relations` endpoint](https://spec.matrix.org/v1.4/client-server-api/#get_matrixclientv1roomsroomidrelationseventid) does not return an `original_event` field, yet the [matrix-bot-sdk uses it](https://github.com/turt2live/matrix-bot-sdk/blob/13ce618976446ac4c8d325acf7aab80a9f5e8d2c/src/UnstableApis.ts#L40-L57).

We would like to remove support for this from Synapse in < 6 months. See matrix-org/synapse#12930 for more context.

**Comment by clokep** [comment]
This seems to mostly just be piping back information from the raw request, so maybe this just needs some documentation updates?

**Comment by turt2live** [comment]
thanks for reporting this <3
