### ISSUE TITLE
Using MatrixClient with RustSdkCryptoStorageProvider fails with an error

### ISSUE THREAD

**Issue by urmaul** [turt2live/matrix-bot-sdk#286]
**Describe the bug**
Trying to run and use MatrixClient with `RustSdkCryptoStorageProvider` fails with an error.

**To Reproduce**
1. Create `RustSdkCryptoStorageProvider` pointing to an empty directory
2. Initialize MatrixClient
3. Try to send or receive a message

**Expected behavior**
Either sending and recieving messages works or I see a meaningful error message.

**Log snippet**
I've got this error when trying to send a message:
```
MatrixHttpClient (REQ-6) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
MatrixClientLite Error handling sync Error: invalid type: map, expected a sequence at line 1 column 0
MatrixClientLite Backing off for 8879.794091495483ms
```

**Additional context**
I don't know how to initialize encryption properly and I couldn't find it in the docs. Should it just work or I should do something more? It created some files in that directory though.

**Comment by AndrewFerr** [comment]
This should have been fixed by https://github.com/turt2live/matrix-bot-sdk/pull/283

**Comment by urmaul** [comment]
Great! Could you please make a new release with this update?

**Comment by AndrewFerr** [comment]
The recently-made Element fork has the fix included in its first release: https://github.com/vector-im/matrix-bot-sdk/releases/tag/v0.6.3-element.0

**Comment by turt2live** [comment]
> Great! Could you please make a new release with this update?

A release is planned for the near future, once a couple other encryption issues are fixed.

----

@AndrewFerr I'd appreciate forks not be advertised here.
