### ISSUE TITLE
Fatal: "No locks available" with example(s)

### ISSUE THREAD

**Issue by digitalextremist** [turt2live/matrix-bot-sdk#317]
Not possible to run the examples ( after `creds` are set properly ) due to error:

```
[Error: IO error: could not acquire lock on "<REPO_ROOT>/matrix-bot-sdk/examples/storage/bot_sled/matrix-sdk-crypto/db": Os { code: 37, kind: Uncategorized, message: "No locks available" }] {
  code: 'GenericFailure'
}
```

Authentication goes fine, it lists off a ton of rooms the bot is already included in ( pre-existing bot user with a lot of unencrypted rooms it is part of ) so I see a ton of these:

```
{ errcode: 'M_NOT_FOUND', error: 'Event not found.' }
```

One for each unencrypted room, then the fatal error at the end.

I noticed this with a hand-made bot example, hit that error ( when using a `cryptoStore` as shown ) and then reproduced it with the examples by invoking a plain:

```
yarn example:bot
```

If all support for encryption is removed, everything works fine... but without encryption.

**Expected behavior**
The bot ought to run with `yarn example:bot` 

... or there needs to be a caveat given in the docs as to why it will break with unencrypted rooms, or there needs to be handling of the unencrypted rooms, if applicable to the example working.

**Log snippet**
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: IO error: could not acquire lock on "<REPO_ROOT>/matrix-bot-sdk/examples/storage/bot_sled/matrix-sdk-crypto/db": Os { code: 37, kind: Uncategorized, message: "No locks available" }] {
  code: 'GenericFailure'
}
```

**Environment**
- `Linux Mint 21.1 with 5.15.0-71` kernel.
- Node: `18.16.0`
- Yarn: `1.22.19`

**Comment by digitalextremist** [comment]
This seems like a local environment issue ( but still worth tracking down ) ... since I was able to launch the examples as-is, within a vanilla `docker` container based on the `node:18` image.

**Comment by turt2live** [comment]
From some quick research, this appears to be a local issue with your NFS setup. The error is coming from your file system, not the bot-sdk
