### ISSUE TITLE
A way to regenerate the description keys.

### ISSUE THREAD

**Issue by CodingBitsDev** [turt2live/matrix-bot-sdk#325]
**Is your feature request related to a problem? Please describe.**
When you remove the encryption folder and the storage of the bot while having encryption enabled all messages sent to the bot end up throwing an error that decryption is not possible.
This is expected behaviour since the bot of course not done any exchange of the encryption keys.
Usually this is either handled by contacting another device, verifying it and receiving the keys in that way, or by entering the the security key to generate the decryption keys. 

**Describe the solution you'd like**
I don't see any way to do this with the matrix-bot-sdk. At least the latter process might be worth implementing.

I might also be wrong and a feature link this already exists. 
Then it might be helpful to update the documentation about a scenario like this.

**Comment by turt2live** [comment]
This would be covered by https://github.com/turt2live/matrix-bot-sdk/issues/143 which requires the rust-sdk bindings to expose the needed functions.

**Comment by CodingBitsDev** [comment]
what rust-sdk are you referting to exactly?

**Comment by turt2live** [comment]
https://github.com/matrix-org/matrix-rust-sdk/
