### ISSUE TITLE
Postgres storage provider should support creation of custom tables and raw SQL

### ISSUE THREAD

**Issue by samip5** [turt2live/matrix-bot-sdk#360]
**Is your feature request related to a problem? Please describe.**
I'm annoyed when I cannot create custom tables with the storage provider, nor execute raw SQL for queries with it.

**Describe the solution you'd like**
The provider should be extended with support for custom tables and potentially raw SQL.

**Describe alternatives you've considered**
Use sqlite db for the part of my bot that requires custom tables.

**Additional context**
I'm building a bot that has a store links that were requested previously, and it doesn't work with the kv store as it should be db row instead.

**Comment by turt2live** [comment]
Custom storage providers are possible. The included one is deliberately feature-less.
