### ISSUE TITLE
Encrypted rooms does not works

### ISSUE THREAD

**Issue by vitonsky** [turt2live/matrix-bot-sdk#363]
**Describe the bug**

Decryption of messages in encrypted rooms always end with error `Error: Can't find the room key to decrypt the event`

**To Reproduce**

Write example code:
```ts
import { MatrixAuth, MatrixClient, RustSdkCryptoStorageProvider, SimpleFsStorageProvider } from 'matrix-bot-sdk';

(async () => {
	const storageProvider = new SimpleFsStorageProvider("./.local/matrix-bot/bot.json"); // or any other IStorageProvider
	const cryptoProvider = new RustSdkCryptoStorageProvider("./.local/matrix-bot/rustCrypto");

	const homeServerUrl = 'https://matrix.org'; // where the bot can reach the homeserver at

	const auth = new MatrixAuth(homeServerUrl);
	const accessToken = await auth.passwordLogin(LOGIN, PASSWORD).then((client) => client.accessToken);
	const client = new MatrixClient(homeServerUrl, accessToken, storageProvider, cryptoProvider);

	// log messages
	client.on("room.message", (_roomId: string, event) => {
		if (!event['content']?.['msgtype']) return;

		// handle message here. It'll be decrypted already.
		console.log("Message event", event);
	});

	// auto join
	client.on("room.invite", (roomId: string, inviteEvent: any) => {
		console.log('inviteEvent', inviteEvent);
		client.joinRoom(roomId);
	});

	// This will set up crypto if needed and prepare the client for automatically decrypting and encrypting messages. Simply
	// use the client like you would without encryption and it should just work.
	client.start().then(() => console.log("Bot started!"));
})();
```

- Replace `LOGIN` and `PASSWORD` to your bot account credentials.
- Run script, for example with `tsx`
- Create chat room with bot from another account with Riot client. Encryption in room must be enabled.
- Send message "Test message"

**Expected behavior**
- Bot join a room
- Bot log message in console

**Actual behavior**
- Bot join a room
- Error `Can't find the room key to decrypt the event` appears in console
- No any messages in logs

Error looks like that:
```
MatrixHttpClient (REQ-48) { errcode: 'M_NOT_FOUND', error: 'Event not found.' }
MatrixClientLite Decryption error on SECRET_ID_HERE:matrix.org SECRET_ID_HERE [Error: Can't find the room key to decrypt the event] {
  code: 'GenericFailure'
}
```

**Additional context**
Messages appears well in case encryption is disabled

**Comment by turt2live** [comment]
The bot-sdk can't handle keys from before its join event.

**Comment by vitonsky** [comment]
> The bot-sdk can't handle keys from before its join event.

How i can change code to make encryption work?

It looks bot-sdk have bug independent of join event.

**Comment by alexgaill** [comment]
> The bot-sdk can't handle keys from before its join event.

This behavior not seems to be the right one. 
this mean that if i want to offer the bot services to everyone in my company I have to ask bot to create a room and invite everybody?

thanks for your answer.

**Comment by Fricsion** [comment]
I'd like a little more in-depth explanation too. 
I've yet to find any documentation that covers how to 
- have a bot login to a server with its `username` & `password` (maybe plus `recovery code`?)
- view & send messages in encrypted rooms & DMs

I was able to achieve this setup one time but not being able to reproduce it.
