### ISSUE TITLE
Support encryption

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-bot-sdk#7]

**Comment by Half-Shot** [comment]
This is solved by https://github.com/turt2live/matrix-js-bot-sdk/commit/c91eb52c6e0f05c23693a7ab992753f86aac3cfb ?

**Comment by turt2live** [comment]
No? There's more to encryption than pantalaimon.

**Comment by n8fr8** [comment]
We've made encryption progress with matrix-js-sdk in our bot here:
https://github.com/guardianproject/ractive/blob/master/bot.js

**Comment by n8fr8** [comment]
that said, it has some issues... would love to get this integrated into your sdk, so we can move to using it and all improve this code together.

**Comment by DanH42** [comment]
Could this limitation get some sort of mention in the readme, or anywhere else in the docs? I just spent over an hour trying to figure out why the echobot example wasn't working for me -- authentication and auto-joining go fine, but then the bot just doesn't receive any events whatsoever after that.

This is also an especially frustrating issue to troubleshoot when you don't know what's causing it: Turning the log level all the way up to TRACE made it clear that the library was getting _something_ whenever I sent a message, but I added listeners for every type of event I could find in the docs and none of them ever fired. I'm not sure if there's anything else I could have done to get some sort of event or exception to let me know that a message the bot has received is encrypted and therefore can't be read, but that's probably something I'll want to be able to handle at some point.

The homeserver I'm using has E2E encryption enabled by default for private chats (which I believe is the out-of-the-box default for Synapse now), so I didn't even think about it until I found this issue. As soon as I added the bot to a new room with encryption disabled, everything started working as expected.

**Comment by n8fr8** [comment]
I realized something working with the new Android SDK2 and the JS SDK in a browser context... when it comes to encrypted messages, you really don't want to be handling incoming events with callbacks. It is better to query the timeline to get to your message backlog. In essence, the event callback should be thought of as a ping, and then you can check the synced timeline for messages you haven't processed yet in your bot, and see if you can decrypt them yet. At some point, once all the remote devices/keys are synced, you will be able to decrypt the message. Often, that can come after you receive the event for the encrypted message payload.
