### ISSUE TITLE
Appservices get request entity too large

### ISSUE THREAD

**Issue by Sorunome** [turt2live/matrix-bot-sdk#73]
Consider something like `this.app.use(express.json({limit: '50mb'}));` or whatever the actual limit as per spec is, if that exists

**Comment by turt2live** [comment]
Largely this is a homeserver bug for sending over so much stuff. Solutions like https://github.com/matrix-org/synapse/issues/3536 would help this

**Comment by Sorunome** [comment]
Would a PR to just up the limit be welcome? Or at least something configurable?

**Comment by Sorunome** [comment]
In [here](https://github.com/matrix-org/matrix-appservice-irc/pull/907/files#diff-c2a2f043131d48ff4e3c3a44d290fdd0) the default is 10M, so perhaps set it to that?

**Comment by turt2live** [comment]
Would accept a PR that just turns off the limit entirely. People can run a reverse proxy if they care to limit it.
