### ISSUE TITLE
prev_content in state events

### ISSUE THREAD

**Issue by Sorunome** [turt2live/matrix-bot-sdk#86]
shouldn't this https://github.com/turt2live/matrix-js-bot-sdk/blob/master/src/models/events/RoomEvent.ts#L80

```
    public get previousContent(): T {
        return this.event['prev_content'] || {};
    }
```

be `this.unsigned['prev_content'] || {};`

**Comment by turt2live** [comment]
Depends on the event, but not really.

**Comment by Sorunome** [comment]
but the `prev_content` is typically in the `unsigned` object, not the root event object?

**Comment by Sorunome** [comment]
After more investigation it seems that synapse and the spec disagree - synapse *sometimes* follows the spec and puts it in the event root, but other times it just puts it in unsigned.

**Comment by turt2live** [comment]
fixed
